/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.sql.*;
import javax.swing.JOptionPane;
import Dao.ModuloConexao;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author damacena
 */
public class frmClientesOut extends javax.swing.JFrame {
     
     Connection conexao = null;
     PreparedStatement pst = null;
     ResultSet rs = null;
     
     
     
     private void salvar(){
         
         String sql = "insert into tb_cliente ( cod_cliente, nome_cliente, sexo_cliente, datnasc_cliente, telefone_cliente, celular_cliente, rg_cliente,cpf_cliente, endereco_cliente, cidade_cliente, estado_cliente, bairro_cliente, cep_cliente, email_cliente, obs_cliente) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
         
         try {
             pst = conexao.prepareStatement(sql);
             
            // pst.setInt(1,Integer.parseInt(txt_Id_Cliente.getText()));           
             pst.setString(1, txt_Cod_Cliente.getText());
             pst.setString(2, txt_Nome_Cliente.getText());
             pst.setString(3, cbo_Sexo_Cliente.getSelectedItem().toString());
             pst.setString(4, txt_Data_Nascimento.getText());
             pst.setString(5, txt_Telefone_Cliente.getText());
             pst.setString(6, txt_Celular_Cliente.getText());
             pst.setString(7, txt_Rg_Cliente.getText()); 
             pst.setString(8, txt_Cpf_Cliente.getText());
             pst.setString(9, txt_Endereco_Cliente.getText());
             pst.setString(10, txt_Cidade_Cliente.getText());
             pst.setString(11, txt_Estado_Cliente.getText());
             pst.setString(12, txt_Bairro_Cliente.getText());
             pst.setString(13, txt_Cep_Cliente.getText());
             pst.setString(14, txt_Email_Cliente.getText());
             pst.setString(15, txt_Obs_Cliente.getText());
             
             
             if ((txt_Cod_Cliente.getText().isEmpty()) || (txt_Nome_Cliente.getText().isEmpty()) || (txt_Endereco_Cliente.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
               
                System.out.println(sql);
                pst.executeUpdate();
             
             
             }else {
       
                int adicionado = pst.executeUpdate();
                System.out.println(adicionado);
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Usuário adicionado com sucesso");
                    txt_Cod_Cliente.setText(null);
                    txt_Nome_Cliente.setText(null);
                    txt_Data_Nascimento.setText(null);
                    txt_Endereco_Cliente.setText(null);
                    txt_Celular_Cliente.setText(null);
                    txt_Email_Cliente.setText(null);
                    txt_Rg_Cliente.setText(null);
                    txt_Cpf_Cliente.setText(null);
                    txt_Obs_Cliente.setText(null);
                    cbo_Sexo_Cliente.setSelectedItem(null);
                    txt_Telefone_Cliente.setText(null);
                    txt_Cidade_Cliente.setText(null);
                    txt_Bairro_Cliente.setText(null);  
                    txt_Cep_Cliente.setText(null);
                    txt_Estado_Cliente.setText(null);

                    

                }
                 
             }
             
         }catch (Exception e){
             
             
             JOptionPane.showMessageDialog(null, e);
             
         }
     }  
     
     /* AQUI VOU IMPLEMENTAR A PESQUISA DO HISTORICO DE COMPRAS DESSE CLIENTE 
     
     private void historico_compras(){
        
         String sql = "select * from  tb_usuario  where nome_usuario like ?";
         
         try{
             pst = conexao.prepareStatement(sql);
             pst.setString(1, txt_Usu_Pesquisa.getText() + "%");
             rs = pst.executeQuery();
             
             tbl_Usu_Pesquisa.setModel(DbUtils.resultSetToTableModel(rs));
         }catch (Exception e){
              JOptionPane.showMessageDialog(null, e);
         }
         
     }*/
    
     
    
    public frmClientesOut() {
        initComponents();
        
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Codigo = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        Data_Nasc = new javax.swing.JLabel();
        Telefone = new javax.swing.JLabel();
        Rg = new javax.swing.JLabel();
        Endereco = new javax.swing.JLabel();
        Cidade = new javax.swing.JLabel();
        Bairro = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();
        Cep = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Obs = new javax.swing.JLabel();
        txt_Data_Nascimento = new javax.swing.JTextField();
        txt_Nome_Cliente = new javax.swing.JTextField();
        txt_Cod_Cliente = new javax.swing.JTextField();
        txt_Cidade_Cliente = new javax.swing.JTextField();
        txt_Telefone_Cliente = new javax.swing.JTextField();
        txt_Endereco_Cliente = new javax.swing.JTextField();
        txt_Rg_Cliente = new javax.swing.JTextField();
        txt_Bairro_Cliente = new javax.swing.JTextField();
        txt_Cep_Cliente = new javax.swing.JTextField();
        txt_Estado_Cliente = new javax.swing.JTextField();
        txt_Email_Cliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Obs_Cliente = new javax.swing.JTextArea();
        txt_Cpf_Cliente = new javax.swing.JTextField();
        txt_Celular_Cliente = new javax.swing.JTextField();
        Sexo = new javax.swing.JLabel();
        Celular = new javax.swing.JLabel();
        Cpf = new javax.swing.JLabel();
        cbo_Sexo_Cliente = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClienteHistorico = new javax.swing.JTable();
        historico_Compras = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Codigo.setText("Código");
        getContentPane().add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        Nome.setText("Nome");
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        Data_Nasc.setText("Data Nasc.");
        getContentPane().add(Data_Nasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        Telefone.setText("Telefone");
        getContentPane().add(Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        Rg.setText("RG");
        getContentPane().add(Rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        Endereco.setText("Endereço");
        getContentPane().add(Endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        Cidade.setText("Cidade");
        getContentPane().add(Cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        Bairro.setText("Bairro");
        getContentPane().add(Bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        Estado.setText("Estado");
        getContentPane().add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 110, -1));

        Cep.setText("CEP");
        getContentPane().add(Cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        Email.setText("Email");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        Obs.setText("Observações");
        getContentPane().add(Obs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        txt_Data_Nascimento.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Data_Nascimento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Data_Nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 157, 32));

        txt_Nome_Cliente.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Nome_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_Nome_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nome_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Nome_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 551, 32));

        txt_Cod_Cliente.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Cod_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Cod_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 111, 32));

        txt_Cidade_Cliente.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Cidade_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Cidade_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 354, 390, 32));

        txt_Telefone_Cliente.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Telefone_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Telefone_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 157, 32));

        txt_Endereco_Cliente.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Endereco_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_Endereco_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Endereco_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Endereco_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 550, 32));

        txt_Rg_Cliente.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Rg_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Rg_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 157, 32));

        txt_Bairro_Cliente.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Bairro_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Bairro_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 394, 390, 32));

        txt_Cep_Cliente.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Cep_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Cep_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 432, 216, 32));

        txt_Estado_Cliente.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Estado_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_Estado_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Estado_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Estado_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 430, 32));

        txt_Email_Cliente.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Email_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_Email_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Email_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Email_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 537, 32));

        txt_Obs_Cliente.setColumns(20);
        txt_Obs_Cliente.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Obs_Cliente.setRows(5);
        txt_Obs_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(txt_Obs_Cliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 582, 104));

        txt_Cpf_Cliente.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Cpf_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Cpf_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 261, 32));

        txt_Celular_Cliente.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Celular_Cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Celular_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 261, 32));

        Sexo.setText("Sexo");
        getContentPane().add(Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        Celular.setText("Celular");
        getContentPane().add(Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        Cpf.setText("CPF");
        getContentPane().add(Cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        cbo_Sexo_Cliente.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cbo_Sexo_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Macho Alfa", "Muié", "Bicha Louca", "Não da para saber" }));
        getContentPane().add(cbo_Sexo_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 270, -1));

        tblClienteHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Data ", "itens", "Valor"
            }
        ));
        jScrollPane2.setViewportView(tblClienteHistorico);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 470, 240));

        historico_Compras.setText("Historico de Compras");
        getContentPane().add(historico_Compras, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 160, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/031-settings.png"))); // NOI18N
        jButton1.setText("Configurações");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 160, 60));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/015-add.png"))); // NOI18N
        jButton2.setText("Novo ");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/020-save.png"))); // NOI18N
        jButton3.setText("Salvar");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 160, 60));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/019-recycle bin.png"))); // NOI18N
        jButton4.setText("Deletar");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 160, 60));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/028-printer.png"))); // NOI18N
        jButton5.setText("Imprimir");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 160, 60));

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cancelar.png"))); // NOI18N
        jButton9.setText("Voltar");
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 160, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, -1));

        setSize(new java.awt.Dimension(1146, 748));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Nome_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nome_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nome_ClienteActionPerformed

    private void txt_Endereco_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Endereco_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Endereco_ClienteActionPerformed

    private void txt_Estado_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Estado_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Estado_ClienteActionPerformed

    private void txt_Email_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Email_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Email_ClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Metodo salvar
        salvar();
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClientesOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClientesOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClientesOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClientesOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClientesOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bairro;
    private javax.swing.JLabel Celular;
    private javax.swing.JLabel Cep;
    private javax.swing.JLabel Cidade;
    private javax.swing.JLabel Codigo;
    private javax.swing.JLabel Cpf;
    private javax.swing.JLabel Data_Nasc;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Endereco;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Obs;
    private javax.swing.JLabel Rg;
    private javax.swing.JLabel Sexo;
    private javax.swing.JLabel Telefone;
    private javax.swing.JComboBox<String> cbo_Sexo_Cliente;
    private javax.swing.JLabel historico_Compras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblClienteHistorico;
    private javax.swing.JTextField txt_Bairro_Cliente;
    private javax.swing.JTextField txt_Celular_Cliente;
    private javax.swing.JTextField txt_Cep_Cliente;
    private javax.swing.JTextField txt_Cidade_Cliente;
    private javax.swing.JTextField txt_Cod_Cliente;
    private javax.swing.JTextField txt_Cpf_Cliente;
    private javax.swing.JTextField txt_Data_Nascimento;
    private javax.swing.JTextField txt_Email_Cliente;
    private javax.swing.JTextField txt_Endereco_Cliente;
    private javax.swing.JTextField txt_Estado_Cliente;
    private javax.swing.JTextField txt_Nome_Cliente;
    private javax.swing.JTextArea txt_Obs_Cliente;
    private javax.swing.JTextField txt_Rg_Cliente;
    private javax.swing.JTextField txt_Telefone_Cliente;
    // End of variables declaration//GEN-END:variables
}
