/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import java.sql.*;
import Dao.ModuloConexao;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author damacena
 */
public class frmUsuariosOut extends javax.swing.JFrame {
     
    Connection conexao = null;
     PreparedStatement pst = null;
     ResultSet rs = null;
     
       private void salvar(){
         
         String sql = "insert into tb_usuario ( nome_usuario, perfil_usuario, telefone_usuario, login_usuario, senha_usuario,email_usuario, obs_usuario ) values (?,?,?,?,?,?,?)";
         
         try {
             pst = conexao.prepareStatement(sql);
             
            // pst.setInt(1,Integer.parseInt(txt_Id_Cliente.getText()));           
             pst.setString(1, txt_Usu_Nome.getText());
             pst.setString(2, cbo_Usu_Perfil.getSelectedItem().toString());
             pst.setString(3, txt_Usu_Telefone.getText());
             pst.setString(4, txt_Usu_Login.getText()); 
             pst.setString(5, txt_Usu_Senha.getText());
             pst.setString(6, txt_Usu_Email.getText());
             pst.setString(7, txt_Usu_Obs.getText());
             
           
             if ((txt_Usu_Nome.getText().isEmpty()) || (txt_Usu_Login.getText().isEmpty()) || (txt_Usu_Celular.getText().isEmpty()) || (txt_Usu_Senha.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
               
                System.out.println(sql);
                pst.executeUpdate();
             
             
             }else {
       
                int adicionado = pst.executeUpdate();
                System.out.println(adicionado);
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Usuário adicionado com sucesso");
                 txt_Usu_Codigo.setText(null);
                    txt_Usu_Nome.setText(null);
                    cbo_Usu_Perfil.setSelectedItem(null);
                    txt_Usu_Telefone.setText(null);
                    txt_Usu_Celular.setText(null);
                    txt_Usu_Login.setText(null);
                    txt_Usu_Senha.setText(null);
                    txt_Usu_Email.setText(null);
                    txt_Usu_Obs.setText(null);

               
                } 
                 
             }
             
         }catch (Exception e){
             
             
             JOptionPane.showMessageDialog(null, "Usuario existente");
             
         }
     }
    
     

    public frmUsuariosOut() {
        initComponents();
        
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_Usu_Nome = new javax.swing.JTextField();
        txt_Usu_Codigo = new javax.swing.JTextField();
        txt_Usu_Telefone = new javax.swing.JTextField();
        txt_Usu_Login = new javax.swing.JTextField();
        txt_Usu_Email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Usu_Obs = new javax.swing.JTextArea();
        txt_Usu_Senha = new javax.swing.JTextField();
        txt_Usu_Celular = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbo_Usu_Perfil = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuLogins = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnSalvarUsuarios = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel4.setText("Telefone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel5.setText("Login");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel13.setText("Email");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabel14.setText("Observações");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txt_Usu_Nome.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Usu_Nome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_Usu_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Usu_NomeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Usu_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 551, 32));

        txt_Usu_Codigo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Usu_Codigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Usu_Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 111, 32));

        txt_Usu_Telefone.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Usu_Telefone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Usu_Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 210, 32));

        txt_Usu_Login.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Usu_Login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Usu_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 210, 32));

        txt_Usu_Email.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Usu_Email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_Usu_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Usu_EmailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Usu_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 550, 32));

        txt_Usu_Obs.setColumns(20);
        txt_Usu_Obs.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Usu_Obs.setRows(5);
        txt_Usu_Obs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(txt_Usu_Obs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 550, 104));

        txt_Usu_Senha.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Usu_Senha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Usu_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 261, 32));

        txt_Usu_Celular.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txt_Usu_Celular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txt_Usu_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 261, 32));

        jLabel16.setText("Perfil");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel17.setText("Celular");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jLabel18.setText("Senha ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        cbo_Usu_Perfil.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cbo_Usu_Perfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        cbo_Usu_Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_Usu_PerfilActionPerformed(evt);
            }
        });
        getContentPane().add(cbo_Usu_Perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 280, 30));

        tblUsuLogins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Data ", "itens", "Valor"
            }
        ));
        jScrollPane2.setViewportView(tblUsuLogins);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 470, 520));

        jLabel19.setText("Historico de logins");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 160, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/031-settings.png"))); // NOI18N
        jButton1.setText("Configurações");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 160, 60));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/015-add.png"))); // NOI18N
        jButton2.setText("Novo ");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        btnSalvarUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/020-save.png"))); // NOI18N
        btnSalvarUsuarios.setText("Salvar");
        btnSalvarUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSalvarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 160, 60));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/019-recycle bin.png"))); // NOI18N
        jButton4.setText("Deletar");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 160, 60));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/028-printer.png"))); // NOI18N
        jButton5.setText("Imprimir");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 160, 60));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/042-prohibition.png"))); // NOI18N
        jButton6.setText("Bloquear");
        jButton6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 160, 60));

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cancelar.png"))); // NOI18N
        jButton9.setText("Voltar");
        jButton9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 160, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, -1));

        setSize(new java.awt.Dimension(1158, 666));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Usu_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Usu_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Usu_NomeActionPerformed

    private void txt_Usu_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Usu_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Usu_EmailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSalvarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarUsuariosActionPerformed
        // Aqui chamo o metodo para salvar usuario.
        salvar();
    }//GEN-LAST:event_btnSalvarUsuariosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Aqui chamo a tela de pesquisa de clientes
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cbo_Usu_PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_Usu_PerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_Usu_PerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsuariosOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsuariosOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsuariosOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsuariosOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsuariosOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarUsuarios;
    private javax.swing.JComboBox<String> cbo_Usu_Perfil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblUsuLogins;
    private javax.swing.JTextField txt_Usu_Celular;
    private javax.swing.JTextField txt_Usu_Codigo;
    private javax.swing.JTextField txt_Usu_Email;
    private javax.swing.JTextField txt_Usu_Login;
    private javax.swing.JTextField txt_Usu_Nome;
    private javax.swing.JTextArea txt_Usu_Obs;
    private javax.swing.JTextField txt_Usu_Senha;
    private javax.swing.JTextField txt_Usu_Telefone;
    // End of variables declaration//GEN-END:variables
}
